// Autogenerated using mud system-types
import { AccountCreateSystem } from "./ethers-contracts/AccountCreateSystem";
import { AccountSetOperatorSystem } from "./ethers-contracts/AccountSetOperatorSystem";
 
export type SystemTypes = {
  "system.AccountCreate": AccountCreateSystem;
  "system.AccountSetOperator": AccountSetOperatorSystem;
};
