// Autogenerated using mud system-types
export const systemToId = {
  AccountCreateSystem: "system.AccountCreate",
  AccountSetOperatorSystem: "system.AccountSetOperator",
};

export const idToSystem = {
  "system.AccountCreate": "AccountCreateSystem",
  "system.AccountSetOperator": "AccountSetOperatorSystem",
};
  