// Autogenerated using mud system-types
import AccountCreateSystem from "../abi/AccountCreateSystem.json";
import AccountSetOperatorSystem from "../abi/AccountSetOperatorSystem.json";

export const SystemAbis = {
  "system.AccountCreate": AccountCreateSystem.abi,
  "system.AccountSetOperator": AccountSetOperatorSystem.abi,
};
